### ISSUE TITLE
不懂Nestjs，了解一些Spring，可以开发吗

### ISSUE THREAD

**Issue by kksh3ll** [nidrs/nidrs#4]
不懂Nestjs，第一次听说这个框架，但是了解一些Spring，做过几年的CRUD，现在学习Rust中，可以开发这个框架吗

**Comment by WumaCoder** [comment]
> 不懂Nestjs，第一次听说这个框架，但是了解一些Spring，做过几年的CRUD，现在学习Rust中，可以开发这个框架吗

感谢你的关注，如果想参与这个项目开发的话可以，可以先加群，后面可以通过分配任务的方式参与贡献😆
